### PR TITLE
Added in yaml file

### PR DESCRIPTION
**Pull request by PatrickGormley**

### CODE REVIEW

**Comment by jflory7** [comment]
@PatrickGormley Most everything is good, but two things you'll need to fix for these to work properly:

1. **Add blog feed**: You'll need to add the RSS feed for your blog in order for ofCourse and the [HFOSS Planet](https://people.rit.edu/djaigm/planet/hfoss/). Blogspot is pretty widely used, so you should be able to find it by either digging around or doing a quick Google search.
2. **Avatar field**: If you don't want to use an avatar, my understanding is that it's better to leave the line out rather than include a blank line. @ritjoe might have to check me on that one, but I'm pretty sure ofCourse / YAML won't like the empty string for that line.

**Comment by jflory7** [comment]
@PatrickGormley Oh, and also don't forget to put the specific link to your First Flight post for the `firstflight` field, and not just the link to your blog. :grin:

**Comment by ritjoe** [comment]
On Mon, Aug 29, 2016 at 09:51:20PM -0700, Justin W. Flory wrote:
> @PatrickGormley Most everything is good, but two things you'll need to fix for
> these to work properly:
> 
>  1. Add blog feed: You'll need to add the RSS feed for your blog in order for
>     ofCourse and the HFOSS Planet. Blogspot is pretty widely used, so you
>     should be able to find it by either digging around or doing a quick Google
>     search.
>  2. Avatar field: If you don't want to use an avatar, my understanding is that
>     it's better to leave the line out rather than include a blank line. @ritjoe
>     might have to check me on that one, but I'm pretty sure ofCourse / YAML
>     won't like the empty string for that line.

Generally, rather than no value, a value of None keeps things moving along.

-- 
Joe

**Comment by PatrickGormley** [comment]
1 / 2 fixed. Stinks that GitHub doesn't support comments on comments

**Pull request merged**
