### PR TITLE
Added the YAML of your valiant TA.

### PR DESCRIPTION
**Pull request by Nolski**
:grapes: :grapes: :grapes: :grapes: :grapes: :grapes: :grapes:

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
lgtm :shipit:

**Comment by jflory7** [comment]
:dart: :dart: :dart: :dart: :dart:

**Comment by liam-middlebrook** [comment]
nevermind `s!GitHub:!- !g

**Comment by Nolski** [comment]
:horse:

**Pull request merged**
