### PR TITLE
Color Legend For Syllabus Schedule v.1

### PR DESCRIPTION
**Pull request by bxs9775**
*Adds a legend to the syllabus page after the schedule, detailing the significance of the colors used in the schedule.
*I was able to check that the table displayed in an appropriate manner. However, I don't know if these changes will break any of the scripts used by the site, as I couldn't get ofcourse working.

### CODE REVIEW

**Comment by ritjoe** [comment]
Thanks, Brian.

Could you go ahead and paste here the text of your earlier email to the class mailing list about the error you saw?

Some of that may end up as an issue, documentation or otherwise, at https://github.com/ryansb/ofcourse but in the meantime it should all probably start here.

**Comment by bxs9775** [comment]
Hello everyone,

I am working on adding a legend under the schedule on the syllabus page of
the HFOSS course site for the Bugfix assignment. I tried checking the page
by copying the html and the css references to an empty html file. This
allows me to see approximately how the page appears and see how my changes
effect things. However, this method does not perfectly reflect how the
code/changes will function on the actual site. I want to try installing and
running ofcourses so I can see how the page works in a setup closer to the
live site, but I am having trouble getting it running.

I am working in the IGM main lab maintained by the Department of
Interactive Games and Media. I have been able to get through installing and
running the python virtualenv. However, when I run $"C:\Program Files
(x86)\Python36-32\Scripts\pip.exe" install ofcourse, the program runs
through most of the installation process before throwing the following
error:

 Command ""c:\program files (x86)\python36-32\python.exe" -u -c "import
setuptools, tokenize;__file__='D:\\Profiles\\bxs9775\\AppData\\
Local\\Temp\\pip-build-2s9p7i4z\\dulwich\\setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
D:\Profiles\bxs9775\AppData\Local\Temp\pip-i5ecgzby-record\install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
D:\Profiles\bxs9775\AppData\Local\Temp\pip-build-2s9p7i4z\dulwich\

Does anyone know why the download would be failing, or how I can get
ofcourses installed?

Thank you,

Brian Sandon

**Comment by bxs9775** [comment]
Update:
I have tried again on my personal laptop. I was missing python from the "path" system environment variable on the lab computer, but I had the variable on my laptop, and the command window can access pip without trouble (at least after I added a "\" to the end of "C:\Python27\Scripts" and "C:\Python27"). I can get through most of the installation but I get the error "Failed building wheel for dulwich" when running $pip install ofcourse or $pip install dulwich. @ritjoe also suggested looking at "PYTHONPATH" in case it is involved in the error. My "PYTHONPATH" system variable lists "%PYTHONPATH%", and "C:\My_python_lib". I am not sure what paths Python needs to reach to access all the necessary libraries, so I am not sure if this is right or not. However, I did check my file browser and there is no folder with the path "My_python_lib" on my C: drive. Does anyone have any suggestions? Thank you for your help.

**Comment by bxs9775** [comment]
Changes moved to pull-request https://github.com/ritjoe/hfoss/pull/369 to prevent the legend changes from getting mixed up with updates to Brian-Sandon.yaml

**Pull request closed without merging**
