### PR TITLE
added my yaml file

### PR DESCRIPTION
**Pull request by siewertsteven**
I hope I did this right

### CODE REVIEW

**Comment by Nolski** [comment]
Almost there. You're missing `rit_dce` as a yaml key and you don't seem to have a bio.

**Comment by ritjoe** [comment]
ofCourse will accept  "rit_dce: None" if you'd prefer. 

I could do it so that it doesn't break the course site, but would rather you did, Steven.

**Comment by siewertsteven** [comment]
I made the changes to the file but I can't seem to be able to commit. Is it because I already have a pull request?

**Comment by ritjoe** [comment]
On Mon, Feb 01, 2016 at 10:46:48AM -0800, siewertsteven wrote:
> I made the changes to the file but I can't seem to be able to commit. Is it
> because I already have a pull request?

Your pending pull request would just get updated, I think.

When you say you can't make the commit, can you copy/paste or screenshot the
error message for us? Is this a problem making the commit to a clone of your
repo on your own computer, or when interacting with github's web interface?


-- 
D. Joe Anderson                        deejoe@mail.rit.edu
Adjunct Faculty              (585) 678-1563 (google voice)   
Interactive Games & Media                       GCCIS, RIT

**Pull request merged**
