### PR TITLE
Updates for latest ofCourse

### PR DESCRIPTION
**Pull request by msoucy**
The latest ofCourse improves support for many things, including jinja templates, and offers some basic macros for the schedule (this will be improved in the future). As part of the change and test data I updated hfoss.

NOTE: This should ONLY be used when using ofCourse v0.2.1 or greater.

### CODE REVIEW

**Comment by msoucy** [comment]
Rebased off of master.

**Comment by Nolski** [comment]
Oops. It looks like this never got merged. @msoucy Do you know if this is still relevant?

**Comment by msoucy** [comment]
Use it as a guideline for the upcoming semester

**Comment by Nolski** [comment]
Sounds good. For now I'll leave it closed to avoid clutter.

**Comment by msoucy** [comment]
So, that "guideline" should definitely be done ASAP, before you get a ton of stuff started in the repo. Part of the reason it wasn't merged last semester was that the repo was very much in flux.

Useful things that were added:

- Using an icalendar editor (google calendar works for this) to make the schedule/assignments/etc
- Cleaned up a lot of the syllabus page

**Comment by Nolski** [comment]
Bringing in @ritjoe on this one. @msoucy it looks like the repo was deleted and I can't reopen the PR?

**Comment by msoucy** [comment]
The commits still appear to be in the pull request? Not entirely sure, honestly. I probably have them on a branch somewhere if you need me to reupload them

**Comment by ritjoe** [comment]
Yeah, pip install grabbed 0.1.12 when I installed, that's what I'm running, so I'm probably not going to get to trying something else for ... a while.

**Pull request closed without merging**
