### PR TITLE
revert back to custom domain

### PR DESCRIPTION
**Pull request by axk4545**
dns may take a bit to propagate fully @ritjoe

### CODE REVIEW

**Comment by ritjoe** [comment]
Accessing your custom domain via https generates the message

    blog.axk4545.me uses an invalid security certificate.

**Comment by axk4545** [comment]
@ritjoe I have no idea what happened to my cert. I added the cloudflare origin cert and it was working for a while but it seems to have broken by the time you looked at it. I am working to fix it with letsencrypt.

**Comment by axk4545** [comment]
@ritjoe should work now. I managed to get Letsencrypt and GitLab to work on the naked domain.

**Comment by axk4545** [comment]
Also added redirects to point blog.axk4545.me and www.axk4545.me at axk4545.me.

**Pull request merged**
