### PR TITLE
New Blog Posts

### PR DESCRIPTION
**Pull request by solanin**

### CODE REVIEW

**Comment by ritjoe** [comment]
The litreview1 link doesn't seem to exist.

Which is fine, since it's not yet due, but the entry in the yaml file should probably come out until that link works.

**Comment by solanin** [comment]
The link does link to the post however only I can see it atm since it is still a draft. That was intentional

**Comment by ritjoe** [comment]
OK, then, please refactor the PR to exclude the link until you're ready for it to go live. I can see no good coming from posting a broken link deliberately: That confounds any search for broken links that are the result of error rather than intention.

**Comment by solanin** [comment]
Well now the link works cause the lit review is published so it should be good to go :)

**Pull request merged**
