### PR TITLE
Added decause.yaml

### PR DESCRIPTION
**Pull request by decause**

### CODE REVIEW

**Comment by msoucy** [comment]
You're not a student, silly!

**Comment by liam-middlebrook** [comment]
:-1:  Website is not http://decau.se please fix

**Comment by ritjoe** [comment]
Nolski has it.  We talked about this before today's class a little bit:  I think some separate "alumni" resource might be a better match.

**Comment by msoucy** [comment]
Where did Nolski say anything in here?

**Comment by liam-middlebrook** [comment]
@ritjoe did you mean me? I was the one who talked with you about that earlier.

**Comment by ritjoe** [comment]
Well, I was referring to you, but talking to decause, but the answer to each
of you grows from the same understanding I have about my role in the course.

To finally get down in black-and-white (well, those are the terminal colors
I'm using now, anyway) what we talked about briefly last Thursday in person:

My view is that there are several layers of abstraction that are relevant to
what "the course" means:  There is the course as it exists in a sort of
present imperfect, persisting over time, and then there's the course as it
exists in the simple present, consisting of each single semester.  

As the instructor for the Fall 2015 course, I have a set of specific and
somewhat more stringent formal obligations to the students enrolled in this
section, and they to me.  Neither I, nor they, have that same formal
relationship to those who have gone before, or those who come afterward.

Which is not to say those ties are not important.  They are.

I think maybe we should look to creating some kind of "course alumni" site
or page to provide for this broader, more meta, continuity.


On Thu, Aug 27, 2015 at 04:42:37PM -0700, Liam Middlebrook wrote:
> @ritjoe did you mean me? I was the one who talked with you about that earlier.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
-- 
Joe   On ceding power to tech companies: http://xkcd.com/1118/
man screen | grep -A2 weird
  A weird imagination is most useful to gain full advantage of
  all the features.

**Pull request closed without merging**
